export interface IProduct {
  id: string,
  ean: string,
  name: string,
  slug: string,
  brand: string,
  title: string,
  active: string,
  brandId: string,
  category: string,
  createdAt: string,
  updatedAt: string,
  categoryId: string,
  fiscalCode: string,
  punctuation: string,
  similarTerms: string,
  displayInSite: boolean,
  longDescription: string,
  approvedByUserId: string,
  displayInSoldOut: boolean,
  shortDescription: string,
  contractAccountId: string,
  commercialPoliticId: string
}
