/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import brands from "../../src/plugins/brands/strapi-admin";
import categories from "../../src/plugins/categories/strapi-admin";
import login from "../../src/plugins/login/strapi-admin";
import contractAccounts from "../../src/plugins/contract-accounts/strapi-admin";
import products from "../../src/plugins/products/strapi-admin";
import salesChannels from "../../src/plugins/sales-channels/strapi-admin";
import stocks from "../../src/plugins/stocks/strapi-admin";
import users from "../../src/plugins/users/strapi-admin";
import collection from "../../src/plugins/collection/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.tsx";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    "strapi-cloud": strapiCloud,
    i18n: i18N,
    "users-permissions": usersPermissions,
    brands: brands,
    categories: categories,
    login: login,
    "contract-accounts": contractAccounts,
    products: products,
    "sales-channels": salesChannels,
    stocks: stocks,
    users: users,
    collection: collection,
  },
});
